networks:
  sync_network:
    driver: bridge

services:
  frontend:
    image: ghcr.io/andras-gerendas/felhohf_frontend:latest
    depends_on:
      - backend
      - kafka
    ports:
      - 5000:5000
    networks:
      - sync_network
  backend:
    image: ghcr.io/andras-gerendas/felhohf_backend:latest
    deploy:
      mode: replicated
      replicas: 6
    depends_on:
      - db_handler
      - kafka
    networks:
      - sync_network
  db_handler:
    image: ghcr.io/andras-gerendas/felhohf_db:latest
    container_name: db_handler
    depends_on:
      - kafka
    networks:
      - sync_network
    volumes:
      - db-data:/app/data
  admin:
    image: ghcr.io/andras-gerendas/felhohf_admin:latest
    depends_on:
      - db_handler
    ports:
      - 5050:5000
    networks:
      - sync_network
  notifier:
    image: ghcr.io/andras-gerendas/felhohf_notifier:latest
    container_name: notifier
    depends_on:
      - db_handler
      - kafka
    ports:
      - 5500:5000
    networks:
      - sync_network
    volumes:
      - sub-data:/app/data
  kafka:
    image: ghcr.io/andras-gerendas/felhohf_kafka:latest
    container_name: kafka
    networks:
      - sync_network

volumes:
  db-data:
  sub-data: