networks:
  sync_network:
    driver: bridge

services:
  frontend:
    image: frontend-test
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 5000:5000
    networks:
      - sync_network
  backend:
    image: backend-test
    container_name: backend
    depends_on:
      - db_handler
    networks:
      - sync_network
  db_handler:
    image: database-test
    container_name: db_handler
    networks:
      - sync_network
  admin:
    image: admin-test
    container_name: admin
    depends_on:
      - db_handler
    ports:
      - 5050:5000
    networks:
      - sync_network
  notifier:
    image: notifier-test
    container_name: notifier
    depends_on:
      - db_handler
      - kafka
    ports:
      - 5500:5000
    networks:
      - sync_network
  kafka:
    image: kafka-test
    container_name: kafka
    networks:
      - sync_network