networks:
  sync_network:
    driver: bridge

services:
  frontend:
    image: frontend-test
    depends_on:
      - backend
      - kafka
    ports:
      - 5000:5000
    networks:
      - sync_network
  backend:
    image: backend-test
    deploy:
      mode: replicated
      replicas: 6
    depends_on:
      - db_handler
      - kafka
    networks:
      - sync_network
  db_handler:
    image: database-test
    container_name: db_handler
    depends_on:
      - kafka
    networks:
      - sync_network
    volumes:
      - db-data:/app/data
  admin:
    image: admin-test
    depends_on:
      - db_handler
    ports:
      - 5050:5000
    networks:
      - sync_network
  notifier:
    image: notifier-test
    container_name: notifier
    depends_on:
      - db_handler
      - kafka
    ports:
      - 5500:5000
    networks:
      - sync_network
    volumes:
      - sub-data:/app/data
  kafka:
    image: kafka-test
    container_name: kafka
    networks:
      - sync_network

volumes:
  db-data:
  sub-data: